name: nexobank_mobile
description: "NexoBank — app móvil bancaria Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  # Estado
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  # Navegación
  go_router: ^14.2.0
  # HTTP
  dio: ^5.4.3
  # Almacenamiento seguro
  flutter_secure_storage: ^9.2.2
  # Caché local
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.3
  # Dinero (nunca double)
  decimal: ^2.3.3
  intl: ^0.20.2
  # WebSocket
  web_socket_channel: ^3.0.1
  # Localización
  flutter_localizations:
    sdk: flutter
  # IDs únicos para idempotency_key
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  mockito: ^5.4.4
  mocktail: ^1.0.4
  isar_generator: ^3.1.0

flutter:
  uses-material-design: true
